### ISSUE TITLE
Create one static 3d level for testing

### ISSUE THREAD

**Issue by Frample** [Degenerate-Games/shadows-below#11]

**Comment by Frample** [comment]
Basic hallway added. Will need some kind of basic player controller added @jameswolff96

**Comment by Frample** [comment]
Level will include Godot meshes, Blender meshes, and slopes, doors, and at least one pitfall for testing.

**Comment by jameswolff96** [comment]
Walls, floors, etc. will need to be children of a StaticBody3D (or RigidBody3D if we want them to be physics enabled) to have collision applied. Once the mesh is a child of a Static or Rigid body select it then select "Mesh" at the top of the 3d editor then click "Create single convex collision sibling"

![image](https://github.com/user-attachments/assets/dcac8dcb-dd64-466e-b68f-74ec6d4bda37)

Afterwards be sure to set the correct collision layers and mask on the Static or Rigid Body, if you hover over the layer number it will give you a description of the layer.

![image](https://github.com/user-attachments/assets/3a10d38f-7ad9-4c53-8ca1-8c0ec683b24d)

**Comment by Frample** [comment]
![Image](https://github.com/user-attachments/assets/b25bd669-cc56-474e-bcdc-bf9bc5cff885)

Created greybox textures and plotted out the test level. ready to test with some mechanics.

**Comment by Frample** [comment]
Closing this, we can use the tutorial level for testing as needed
